### ISSUE TITLE
의상 분류 모델용 데이터 정제❌

### ISSUE THREAD

**Issue by Jiwonii97** [team-naming-1-hour/sweater_ai#10]
더 높은 성능의 분류 모델을 위해 중복&잘못 분류된 데이터를 정제한다.

![image](https://user-images.githubusercontent.com/79522982/160429192-21f31010-7615-4af7-b2b3-84e7602a1912.png)

Done 조건 : 본인이 맡은 카테고리에 대해 작업을 진행하고 29일 스탠드업 이후 각자 데이터를 확인후 완료된 것을 합쳐서 드라이브에 올리면 Done

**Comment by dev2820** [comment]
무신사 데이터 정제 결과 중복을 제거하고 나니 각 카테고리의 데이터가 100여개 정도 안되게 남아 추가적으로 현대몰과 11번가 데이터 분류도 하기로 했다.

**Comment by dev2820** [comment]
❌ deep fashion 데이터 셋에서 낮은 정확도의 분류를 보여 모델 개발을 포기하고 구글 vision api를 사용하기로 함
