### ISSUE TITLE
의상 크롭

### ISSUE THREAD

**Issue by Jiwonii97** [team-naming-1-hour/sweater_ai#8]
YOLO로 의상을 상하의 잘라 한 폴더에 저장한다. (사진당 1폴더)

Done 조건 : YOLO로 나눈 사진이 디렉토리로 분류되는 것을 확인하고 테스트 결과를 봤을때 정확히 분류되는 것을 확인하면 Done

**Comment by dev2820** [comment]
@Jiwonii97 인스타 사진 100장 무작위로 뽑아서 크롭 테스트 진행하고 결과 공유해주세요(얼만큼의 정확도를 가지는지, 어떤 사진들을 잘못 분류했는지 등등)
